services:
  minio:
    image: minio/minio
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server /data
    volumes:
      - "C:/filend/minio:/data"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: filend
    ports:
      - "5432:5432"
    volumes:
      - "C:/filend/pg:/data"

  app:
    build: .
    ports:
      - "9091:9091"
    depends_on:
      - minio
      - postgres
    env_file:
      - .env